name: 'dbt-docs CD'

on:
  pull_request: 
    types:
      - closed 
    branches:
      - main

defaults:
  run:
    shell: bash
  
jobs:
  release_data_catalog:
    name: 'Release dbt-docs'
    if: startsWith(github.base_ref, 'generate/v')
    runs-on: ubuntu-latest
    steps:

      - name: 'Git Checkout'
        uses: actions/checkout@v3

      - name: 'Split branch name'
        id: get_tag_version        
        env:
          BRANCH: ${{ github.base_ref }}
        run: |
          echo "RELEASE_VERSION=${BRANCH##generate/}"  >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION }}
        
        
      - name: 'Install submodules'
        run: git submodule update --init --recursive

      - name: 'Debug version'
        run: echo $RELEASE_VERSION

      - name: 'Setup Node.js v14.18.2'
        uses: actions/setup-node@v3
        with:
          node-version: 14.18.2

      - name: 'Setup Ruby v2.7.5'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: 'Build the css files required for webpack'
        run: |
          cd styles
          bundle exec jekyll build
          cd -
      
      - name: 'Download the package and dependencies'
        run: npm install

      - name: 'Build website'
        run: npx webpack
      
      - name: 'Create release'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: dbt-docs
          tag_name: "catalog_${{ env.RELEASE_VERSION}} "
          generate_release_notes: true
          files: dist/index.html

      - name: 'Publish release'
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
